name: Deploy Svelte App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Change directory to myapp
        run: cd myapp
        
      - name: Install dependencies
        run: |
          cd myapp
          npm run build

      - name: Build Svelte app
        run: |
          cd myapp
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: myapp/dist
